# Generated by Django 5.0.4 on 2024-07-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
