# Generated by Django 5.0.4 on 2024-08-07 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('reward_points', models.IntegerField(default=0, null=True)),
                ('battery_level', models.IntegerField(null=True)),
                ('charge_status', models.BooleanField(null=True)),
                ('power_consumption', models.FloatField(null=True)),
                ('battery_status', models.IntegerField(null=True)),
                ('picked_up', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BinCompartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_waste', models.CharField(choices=[('RECYCLABLE', 'RECYCLABLE'), ('NON_RECYCLABLE', 'NON_RECYCLABLE')], max_length=20)),
                ('temperature', models.FloatField(null=True)),
                ('weight', models.FloatField(default=0, null=True)),
                ('bin_level', models.IntegerField(null=True)),
                ('parent_bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartments', to='dashboard.wastebin')),
            ],
        ),
        migrations.CreateModel(
            name='WasteBinRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('date_requested', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('delivered', models.BooleanField(default=False)),
                ('date_delivered', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WastePickUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('RECYCLABLE', 'RECYCLABLE'), ('NON_RECYCLABLE', 'NON_RECYCLABLE')], max_length=20)),
                ('reward_gained', models.IntegerField(null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('picked_up', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_picked', models.DateTimeField()),
                ('parent_bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.wastebin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
