# Generated by Django 5.0.4 on 2024-08-07 06:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WasteBinRequests',
            new_name='WasteBinRequest',
        ),
    ]
