# Generated by Django 5.0.4 on 2024-08-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_wastebinrequest_date_delivered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastepickup',
            old_name='confirmed',
            new_name='completed',
        ),
    ]
