# Generated by Django 5.0.4 on 2024-08-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_confirmed_wastepickup_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastebin',
            name='picked_up',
        ),
        migrations.AlterField(
            model_name='wastebin',
            name='battery_status',
            field=models.CharField(choices=[('FULL', 'FULL'), ('LOW', 'LOW'), ('OKAY', 'OKAY')], default=0, max_length=20),
        ),
    ]
