# Generated by Django 5.0.4 on 2024-08-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_wastebin_picked_up_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastebin',
            name='battery_status',
            field=models.CharField(choices=[('FULL', 'FULL'), ('LOW', 'LOW'), ('OKAY', 'OKAY')], default=None, max_length=20),
        ),
    ]
